{
 "title": "Kafka Minion",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": "label_values(kafka_minion_group_topic_partition_offset, group)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_minion_group_topic_partition_offset{group=\"$consumer_group\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Topic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Count $topic",
   "type": "graph",
   "description": "Message count is only the difference between all partitions' high and low watermarks. Therefore this count is only an approximation on compact topics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (sum by (kubernetes_pod_name) (kafka_minion_topic_partition_message_count{topic=\"$topic\"}))",
     "legendFormat": "Approx Messages"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (kafka_minion_topic_partition_count{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Cleanup Policy",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "kafka_minion_topic_partition_count{topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Groups consuming $topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by (group, topic) (kafka_minion_group_topic_lag{topic=\"$topic\"})"
    }
   ]
  },
  { "title": "Group metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (group,topic) (kafka_minion_group_topic_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "{{group}} => {{topic}}"
    }
   ]
  },
  {
   "title": "Offset Commit Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum by (kubernetes_pod_name) (rate(kafka_minion_group_topic_partition_commit_count{group=\"$consumer_group\", topic=\"$topic\"}[1m])))"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_minion_group_topic_lag{group=\"$consumer_group\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (sum by (topic, kubernetes_pod_name) (delta(kafka_minion_group_topic_partition_offset{group=\"$consumer_group\", topic=\"$topic\"}[1m]) / 60))",
     "legendFormat": "Consuming: {{$consumer_group}} => {{$topic}}"
    },
    {
     "expr": "avg by (topic) (sum by (topic, kubernetes_pod_name) (delta(kafka_minion_topic_partition_high_water_mark{topic=\"$topic\"}[1m]) / 60))",
     "legendFormat": "Incoming: {{ topic }}"
    }
   ]
  },
  {
   "title": "Lag per Partition: $consumer_group => $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (group,topic,partition) (kafka_minion_group_topic_partition_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "Partiton {{partition}}"
    }
   ]
  },
  {
   "title": "Partition Offsets",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max by (topic, partition) (kafka_minion_topic_partition_low_water_mark{topic=\"$topic\"})"
    },
    {
     "expr": "max by (topic, partition) (kafka_minion_topic_partition_high_water_mark{topic=\"$topic\"})"
    },
    {
     "expr": "max by (topic, partition) (kafka_minion_group_topic_partition_offset{topic=\"$topic\", group=\"$consumer_group\"})"
    },
    {
     "expr": "max by (topic, partition) (kafka_minion_group_topic_partition_lag{topic=\"$topic\", group=\"$consumer_group\"})"
    },
    {
     "expr": "max by (topic, partition) (kafka_minion_topic_partition_message_count{topic=\"$topic\"})"
    },
    {
     "expr": "max by (topic, partition) (kafka_minion_group_topic_partition_last_commit{topic=\"$topic\", group=\"$consumer_group\"})"
    }
   ]
  },
  { "title": "Kafka Minion Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Offset commits processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name) (rate(kafka_minion_internal_kafka_messages_in_success[1m]))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}